service: ${self:custom.serviceName}

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-plugin-scripts
  - serverless-offline
  - serverless-lift

package:
  excludeDevDependencies: false

custom:
  serviceName: nhl
  schedulerName: game-scheduler
  watcherName: game-watcher
  apiName: game-api
  common: ${file(./secrets.yml)}

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  timeout: 60
  profile: serverless-admin2
  region: us-east-1
  stage: dev
  environment:
    # This environment section is used for all functions in the config
    # This is a commonly used access token for all lambda handling
    REGION: ${opt:region, self:provider.region}
    STAGE: ${opt:stage, self:provider.stage}

functions:
  game-scheduler:
    name: game-scheduler
    handler: game-scheduler/src/index.handler
    description: Triggers loads for all games
    events:
      - schedule:
          rate: rate(12 hours)
          name: every-12-hours

  game-watcher:
    name: game-watcher
    handler: game-watcher/src/index.handler
    description: Triggers loads for all games
    events:
      - sqs: arn:aws:sqs:region:${self:custom.common.AWS_ACCOUNT_ID}:record-game-data
