service: ${self:custom.serviceName}

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-plugin-scripts
  - serverless-offline

package:
  excludeDevDependencies: false

custom:
  serviceName: nhl
  fname: game-scheduler
  common: ${file(../secrets.yml)}

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  timeout: 60
  profile: serverless-admin2
  region: us-east-1
  stage: dev
  # role: arn:aws:iam::${self:custom.common.AWS_ACCOUNT_ID}:role/lambda_execution_withdb
  environment:
    # This environment section is used for all functions in the config
    # This is a commonly used access token for all lambda handling
    REGION: ${opt:region, self:provider.region}
    STAGE: ${opt:stage, self:provider.stage}

functions:
  game-scheduler:
    name: ${self:custom.fname}
    handler: src/index.handler

    description: Triggers loads for all games
    events:
      - sns: load-live-data
      - sns: ${self:custom.fname}
      - schedule:
          rate: cron(30 * * * ? *)
          name: every-12-hours
